<a href="https://colab.research.google.com/github/phani-x507/DeepLearning/blob/main/Pytorch/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [3]:
# Introduction to Tensors
# Creating Tensors

In [4]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item() # Returns the Item in Tensor

7

In [7]:
vector = torch.tensor([7,7]) #SINGLE DIMENSION IS CALLED VECTOR
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,7]]) #MULTI DIMENSION ARE CALLED MATRIX0
MATRIX

tensor([[7, 7]])

In [11]:
MATRIX.shape

torch.Size([1, 2])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR.ndim

3

#Random Tensors
 - Create tensor, see how it respesenting the dat and adjust the random values.


In [17]:
# Create a Ranodm Tensors of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7086, 0.0268, 0.4215, 0.6870],
        [0.3631, 0.3811, 0.4308, 0.1826],
        [0.7225, 0.2732, 0.4078, 0.6685]])

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9747, 0.5374, 0.7426, 0.8320],
        [0.2075, 0.7717, 0.6573, 0.0338],
        [0.5218, 0.9519, 0.5028, 0.2549]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones

In [21]:
zeros = torch.zeros(size =(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Tensor Datatypes

# Float 32 tensor
**Note**: Tensor datatypes is one the 3 big errors you run into pythorch and deeplearning
1. Tensors not right datatype
2. Tensors not right ShapeType
3. Tensors not on the right device

In [24]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                             device = None, #CPU, Cuda or None(Defaults CPU)
                             dtype = None #torch.float32,16,64 or any.
                              )
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
# Convert Tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [27]:
# Details of Tensor.
print("Data Type : ",float_16_tensor.dtype)
print("Shape of a Tensor :", float_16_tensor.shape )
print("Device tensor is on:", float_32_tensor.device)

Data Type :  torch.float16
Shape of a Tensor : torch.Size([3])
Device tensor is on: cpu
