<a href="https://colab.research.google.com/github/phani-x507/DeepLearning/blob/main/Pytorch_Fundamentals_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.2060, 0.8913, 0.3806, 0.0144, 0.4073, 0.2025, 0.8861],
        [0.4868, 0.1976, 0.3596, 0.2987, 0.4561, 0.4086, 0.4149],
        [0.6862, 0.2206, 0.8992, 0.4371, 0.3836, 0.7175, 0.6788],
        [0.2618, 0.3942, 0.3558, 0.3510, 0.6688, 0.8123, 0.6029],
        [0.5933, 0.0548, 0.5607, 0.1367, 0.7802, 0.1895, 0.3700],
        [0.9625, 0.5908, 0.6945, 0.8951, 0.6476, 0.4813, 0.3142],
        [0.5994, 0.0108, 0.3135, 0.1744, 0.0742, 0.5688, 0.2862]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor1 = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(tensor,tensor1.T)

tensor([[1.3475],
        [1.1499],
        [1.8098],
        [1.4035],
        [1.0501],
        [2.0814],
        [1.1394]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_a = torch.rand(1,9).reshape(3,3)
tensor_b = torch.rand(1,9).reshape(3,3)

# Matrix multiply tensors
torch.matmul(tensor_a,tensor_b)


tensor([[0.3768, 0.3646, 0.4959],
        [0.4191, 0.5404, 0.6507],
        [0.5662, 0.6402, 0.8248]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed_all(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [25]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
# Create two random tensors on GPU
randomA = torch.rand(2,3).to(device)
randomB = torch.rand(2,3).to(device)
randomA,randomB

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
outputTensor = torch.matmul(randomA,randomB.T)
outputTensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [31]:
# Find max
torch.max(outputTensor)

# Find min
torch.min(outputTensor)


tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [33]:
# Find arg max
torch.argmax(outputTensor)

# Find arg min
torch.argmin(outputTensor)


tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [41]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensorTEN = torch.rand(1,1,1,10)

# Remove single dimensions
newTensor =  tensorTEN.reshape(10)
# Print out tensors and their shapes
print(tensorTEN,tensorTEN.shape)
print(newTensor,newTensor.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
