<a href="https://colab.research.google.com/github/phani-x507/DeepLearning/blob/main/Pytorch_Tensors_and_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch tensors And Numpy
Convert Numpy to pytorch tensor ->  `torch.from_numpy(ndarray)`
PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [5]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [6]:
array.dtype #Numpy creates float64 by default

dtype('float64')

In [7]:
tensor.dtype # After conversion tensor adapts the dtype of numpy

torch.float64

In [10]:
torch.arange(1.0,7.0).dtype #Tensor creates float32 by default

torch.float32

In [13]:
#if we want to change it to float 32
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [15]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor.dtype

dtype('float32')

# Reproducibility
* Reproducibility in PyTorch means getting the same results (or very close) every time you run your code—especially important for debugging, research, and comparing experiments.
* It is used to produce near to similar random numbers everytime to get same randomness in sample data every time running the code.

In [18]:
## Reproducibility (Trying to pick random from random numbers )
tensorA = torch.rand(3,3)
tensorB = torch.rand(3,3)
print(tensorA)
print(tensorB)
print(tensorA == tensorB)

tensor([[0.3099, 0.1418, 0.1746],
        [0.3024, 0.7944, 0.9214],
        [0.9013, 0.7853, 0.9451]])
tensor([[0.7087, 0.5553, 0.0030],
        [0.8497, 0.7224, 0.4118],
        [0.5744, 0.4930, 0.6823]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [19]:
## We can use manual seed for reproducibility
RANDOM_SEED = 43
torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(3,3)
tensorB = torch.rand(3,3)
print(tensorA == tensorB) # So tensorA and tensorB is not created same results

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [20]:
# Lets to like this
torch.manual_seed(RANDOM_SEED)
tensorA = torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
tensorB = torch.rand(3,3)
print(tensorA == tensorB) # it created same results

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [1]:
# Check for GPU Access
import torch
torch.cuda.is_available()

True

In [2]:
!nvidia-smi

Wed Mar 25 09:46:21 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
# Device Agnoustic Code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
# Count number of cuda Devices
torch.cuda.device_count()

1

In [8]:
# Lets create a tensor
tensor = torch.rand(3)
tensor.device #So by default tensor is created by cpu

device(type='cpu')

In [12]:
#Lets move it to GPU
tensorGPU = tensor.to(device)
tensorGPU # Here we successfully converted to GPU

tensor([0.1105, 0.9774, 0.4196], device='cuda:0')

In [17]:
# Now Convert into NumPy array
# tensorGPU.numpy() -> it shows error,
#can't convert cuda:0 device type tensor to numpy.
#Use Tensor.cpu() to copy the tensor to host memory first.

# So we need to shift that to cpu then convert it to numpy

tensorCPU = tensorGPU.cpu().numpy()
tensorCPU,tensorCPU.device #Conversion Successful


(array([0.11050856, 0.977362  , 0.41958094], dtype=float32), 'cpu')