<a href="https://colab.research.google.com/github/phani-x507/DeepLearning/blob/main/Pytorch/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [3]:
# Introduction to Tensors
# Creating Tensors

In [4]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item() # Returns the Item in Tensor

7

In [7]:
vector = torch.tensor([7,7]) #SINGLE DIMENSION IS CALLED VECTOR
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,7]]) #MULTI DIMENSION ARE CALLED MATRIX0
MATRIX

tensor([[7, 7]])

In [11]:
MATRIX.shape

torch.Size([1, 2])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,4,5],[5,6,7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR.ndim

3

#Random Tensors
 - Create tensor, see how it respesenting the dat and adjust the random values.


In [17]:
# Create a Ranodm Tensors of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7796, 0.5454, 0.3894, 0.7016],
        [0.0394, 0.8179, 0.6649, 0.4435],
        [0.2189, 0.0218, 0.5640, 0.8681]])

In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7797, 0.1363, 0.6139, 0.8477],
        [0.0684, 0.8403, 0.6677, 0.2940],
        [0.1667, 0.9276, 0.5731, 0.1725]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224))
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

# Zeros and Ones

In [21]:
zeros = torch.zeros(size =(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a tensor ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

# Tensor Datatypes

# Float 32 tensor
**Note**: Tensor datatypes is one the 3 big errors you run into pythorch and deeplearning
1. Tensors not right datatype
2. Tensors not right ShapeType
3. Tensors not on the right device

In [24]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                             device = None, #CPU, Cuda or None(Defaults CPU)
                             dtype = None #torch.float32,16,64 or any.
                              )
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
# Convert Tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [27]:
# Details of Tensor.
print("Data Type : ",float_16_tensor.dtype)
print("Shape of a Tensor :", float_16_tensor.shape )
print("Device tensor is on:", float_32_tensor.device)

Data Type :  torch.float16
Shape of a Tensor : torch.Size([3])
Device tensor is on: cpu


### Manipulating Tensors(tensor Operations)
  - Addition
  - Subraction
  - Multiplication (Element Wise)
  - Division
  - Matrix Multiplication

In [28]:
# Addition
tensor = torch.tensor([[1,2,3],
                       [4,5,6]])
tensor + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [29]:
# Multiplication
tensor * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [30]:
# Subraction
tensor - 10

tensor([[-9, -8, -7],
        [-6, -5, -4]])

In [31]:
# Pytorch inbuilt function Multiplication
torch.mul(tensor,19)

tensor([[ 19,  38,  57],
        [ 76,  95, 114]])

In [32]:
torch.add(tensor,10)

tensor([[11, 12, 13],
        [14, 15, 16]])

In [33]:
torch.div(tensor,10)

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])

In [34]:
torch.sub(tensor,20)

tensor([[-19, -18, -17],
        [-16, -15, -14]])

# Matrix Multiplication
 Two main ways of performing Matrix Multiplication
 1. Element wise
 2. Matrix Multiplication (Dot Product)

In [35]:
# Element Wise.
tensor = torch.tensor([1,2,3])
tensor * tensor
#1*1, 2*2, 3*3

tensor([1, 4, 9])

In [36]:
# Matrix Multiplication using torch.matmul()
torch.matmul(tensor,tensor)
# 1*1+2*2+3*3 = 14

tensor(14)

In [37]:
ones = np.ones((3,3))
ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
tensor = torch.tensor(ones)
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [39]:
tensor2 = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float64)
tensor2

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [40]:

#Two dimensions should be equal to perform this
# if you do dotproduct then shape of column of 1st matrix should be equal to
# shape of rows on second matrix ex: 3x2 * 2*3
# if shape is same it works too
torch.matmul(tensor2,tensor)

tensor([[ 6.,  6.,  6.],
        [15., 15., 15.]], dtype=torch.float64)

In [41]:
# Transpose
# we can do this if changing dimension helps to make dotproduct possible
print(f"Tensor1 Shape : {tensor.shape} and Tensor2 Shape : {tensor2.shape} ")
print(f"The inner dimensions doesnot match so, we can transpose")
print(f"Transposed Tensor2 = {tensor2.T} and shape is {tensor2.T.shape}")
print(f"Now Multiplying these two will get \n {torch.matmul(tensor,tensor2.T)}")

Tensor1 Shape : torch.Size([3, 3]) and Tensor2 Shape : torch.Size([2, 3]) 
The inner dimensions doesnot match so, we can transpose
Transposed Tensor2 = tensor([[1., 4.],
        [2., 5.],
        [3., 6.]], dtype=torch.float64) and shape is torch.Size([3, 2])
Now Multiplying these two will get 
 tensor([[ 6., 15.],
        [ 6., 15.],
        [ 6., 15.]], dtype=torch.float64)


## Tensor Aggregations
  - Min, Max, Sum, Mean  etc..

In [42]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
#Find Max
torch.max(x),x.max

(tensor(90), <function Tensor.max>)

In [44]:
#Find the Mean if it is int change it to Float or Complex types
torch.mean(x.type(torch.float32)) #Only works with Floating Point or Complex Numbers

tensor(45.)

In [45]:
#Sum of All elements
torch.sum(x)

tensor(450)

In [46]:
#Find Minimum
torch.min(x)

tensor(0)

#Finding the Positional min and max
 - x.argmin() and x.argmax()
 - gives the index of respective minimum and maximum values

In [47]:
#Find Minimum Position
x.argmin()

tensor(0)

In [48]:
#Find Maximum Position
print(f"Maxmimum value Index {x.argmax()} and value : {x[x.argmax()]}")

Maxmimum value Index 9 and value : 90


# Reshaping, Stacking, Squeezing, and Unsqueezing Tensors
  - Reshaping : Reshapes the tensor to different dimensions
  - View : Returns the view of a original tensor
  - Stacking : Combining Multiple Tensors
  - Squeeze : Removes all 1 Dimension From a tensor
  - Unsqueeze : Add a 1 dimension to a target tensor
  - Permute : Return a view of the input with dimensions permuted(Swapped) in a certain way

In [49]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# Now the possible reshapes are the factors of total items
torch.reshape(x,(3,3))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
torch.reshape(x,(1,9))

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
torch.reshape(x,(9,1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [53]:
# Adds Another Dimension but directs to same memory of original
# Change in value of a view changes in original array
z = x.view(3,3)
z[1,0] = 55
z," ",x

(tensor([[ 1,  2,  3],
         [55,  5,  6],
         [ 7,  8,  9]]),
 ' ',
 tensor([ 1,  2,  3, 55,  5,  6,  7,  8,  9]))

In [54]:
#Stacking means Adding elements to existing matix horizontally or vertically
# stack(),hstack(),vstack()
# Creates another dimension and does manipulation
# dim = 0 (row) -> Vstack() , dim = 1(column) -> hstack(), dim = 0 by default
y = torch.arange(0,90,10)
y = y.reshape(3,3)
y_stacked = torch.stack([z,y],dim=1)
y_stacked

tensor([[[ 1,  2,  3],
         [ 0, 10, 20]],

        [[55,  5,  6],
         [30, 40, 50]],

        [[ 7,  8,  9],
         [60, 70, 80]]])

In [55]:
x = x.view(1,9)
x,'Original Dimension',x.shape

(tensor([[ 1,  2,  3, 55,  5,  6,  7,  8,  9]]),
 'Original Dimension',
 torch.Size([1, 9]))

In [56]:
x.squeeze(),'After Squeezing',x.squeeze().shape # Removes all single Dimensions

(tensor([ 1,  2,  3, 55,  5,  6,  7,  8,  9]),
 'After Squeezing',
 torch.Size([9]))

In [57]:
x.unsqueeze(dim=1),'After Unsqueezing', x.unsqueeze(dim=1).shape #Adds 1 Dimension

(tensor([[[ 1,  2,  3, 55,  5,  6,  7,  8,  9]]]),
 'After Unsqueezing',
 torch.Size([1, 1, 9]))

In [71]:
#torch.permute() -> rearranges the dimensions of a target tensor in specified order.
image = torch.rand(size=(255,255,3))
print('Sampe of Image : ',image.shape)
permuted = image.permute(dims=(2,0,1))
print('Shape of Permuted', permuted.shape)


Sampe of Image :  torch.Size([255, 255, 3])
Shape of Permuted torch.Size([3, 255, 255])


In [74]:

print(permuted[0,0,0])
permuted[0,0,0] = 0.7456
print(permuted[0,0,0])

tensor(0.0303)
tensor(0.7456)


## Indexing (Selecting Data from Tensors with Indexing)
Indexing with PyTorch is similar with NumPy

In [76]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3) #Three Dimensional

In [77]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [79]:
#Lets index on our new tensor dim=0
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
# Lets index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [81]:
# Lets index to Last Dimension(dim =3)
x[0][0][0]

tensor(1)

In [82]:
#Get all values of -th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [84]:
# Get all values of the 0 dimenstion but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [92]:
# Get index 0 of 0th and 1st dimenstion and all values of 2nd dimension
x[0:,0,:]

tensor([[1, 2, 3]])

In [94]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [101]:
# Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])